apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: platform-postgres
  namespace: platform
spec:
  teamId: "platform"
  volume:
    size: 50Gi
    storageClass: fast-ssd
  numberOfInstances: 2
  users:
    # Database users will be created automatically
    zalando:
    - superuser
    - createdb
  databases:
    authentik: zalando
    backstage: zalando
    harbor: zalando
    argo_workflows: zalando
  postgresql:
    version: "15"
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 2000m
      memory: 2Gi
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  connectionPooler:
    numberOfInstances: 2
    mode: transaction
    schema: pooler
    user: pooler
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

