apiVersion: batch/v1
kind: Job
metadata:
  name: vault-schema-init
  namespace: platform
  labels:
    app.kubernetes.io/name: vault-schema-init
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/managed-by: argocd
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: PGHOST
          value: platform-postgres.platform.svc.cluster.local
        - name: PGPORT
          value: "5432"
        - name: PGDATABASE
          value: vault
        - name: PGUSER
          value: zalando
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: zalando.platform-postgres.credentials.postgresql.acid.zalan.do
              key: password
        - name: PGSSLMODE
          value: require
        command:
        - /bin/sh
        - -c
        - |
          set -e
          
          echo "Creating vault_kv_store table..."
          psql -c "
          CREATE TABLE IF NOT EXISTS vault_kv_store (
            parent_path TEXT COLLATE \"C\" NOT NULL,
            path        TEXT COLLATE \"C\",
            key         TEXT COLLATE \"C\",
            value       BYTEA,
            CONSTRAINT pkey PRIMARY KEY (path, key)
          );"
          
          echo "Creating parent_path_idx index..."
          psql -c "CREATE INDEX IF NOT EXISTS parent_path_idx ON vault_kv_store (parent_path);"
          
          echo "Creating vault_ha_locks table..."
          psql -c "
          CREATE TABLE IF NOT EXISTS vault_ha_locks (
            ha_key                                      TEXT COLLATE \"C\" NOT NULL,
            ha_identity                                 TEXT COLLATE \"C\" NOT NULL,
            ha_value                                    TEXT COLLATE \"C\",
            valid_until                                 TIMESTAMP WITH TIME ZONE NOT NULL,
            CONSTRAINT ha_key PRIMARY KEY (ha_key)
          );"
          
          echo "Vault schema initialization completed successfully!"
      backoffLimit: 3

