apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: security
    app.kubernetes.io/name: authentik-external-secrets
spec:
  destination:
    namespace: authentik
    server: https://kubernetes.default.svc
  project: security
  source:
    repoURL: ${GIT_REPO_URL}
    targetRevision: HEAD
    path: argocd/app-of-apps/apps/security/authentik-external-secrets.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

