apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: security
    app.kubernetes.io/name: external-secrets
spec:
  destination:
    namespace: external-secrets-system
    server: https://kubernetes.default.svc
  project: security
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.10.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      namespace: external-secrets-system
      jsonPointers:
        - /data
    - group: ""
      kind: ConfigMap
      namespace: external-secrets-system
      jsonPointers:
        - /data


