apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-postgres-connection
  namespace: vault
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: vault
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: vault-postgres-connection
    creationPolicy: Owner
  data:
    - secretKey: connection_url
      remoteRef:
        key: platform/vault/postgres-connection-url

