apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: security
    app.kubernetes.io/name: vault-external-secrets
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: security
  source:
    repoURL: https://github.com/alanredfordhayes/platform.git
    targetRevision: main
    path: argocd/app-of-apps/apps/security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

