apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: automation
    app.kubernetes.io/name: argo-workflows
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: automation
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: 0.47.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      namespace: argo
      jsonPointers:
        - /data
    - group: ""
      kind: ConfigMap
      namespace: argo
      jsonPointers:
        - /data


