apiVersion: v1
kind: Secret
metadata:
  name: hashicorp-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: https://helm.releases.hashicorp.com
  # Helm OCI repositories don't require credentials for public repos
  # For private Helm repos, add:
  # username: your-username
  # password: your-token

