apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: platform
    app.kubernetes.io/name: postgresql-cluster
spec:
  destination:
    namespace: platform
    server: https://kubernetes.default.svc
  project: automation
  source:
    repoURL: https://github.com/alanredfordhayes/platform.git
    targetRevision: main
    path: argocd/app-of-apps/apps/platform/postgresql-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

