apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: platform
    app.kubernetes.io/name: postgres-operator-ui
spec:
  destination:
    namespace: postgres-operator
    server: https://kubernetes.default.svc
  project: automation
  source:
    repoURL: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
    chart: postgres-operator-ui
    targetRevision: 1.10.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

