apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: platform
    app.kubernetes.io/name: redis
spec:
  destination:
    namespace: platform
    server: https://kubernetes.default.svc
  project: automation
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: <latest-version>  # Use Context7 MCP to get latest version
    helm:
      valueFiles:
        - $values/redis-values.yaml
      values: |
        architecture: replication
        auth:
          enabled: true
          password: "env://REDIS_PASSWORD"
        master:
          persistence:
            enabled: true
            size: 10Gi
            storageClass: fast-ssd
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
        replica:
          replicaCount: 2
          persistence:
            enabled: true
            size: 10Gi
            storageClass: fast-ssd
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      namespace: platform
      jsonPointers:
        - /data
    - group: ""
      kind: ConfigMap
      namespace: platform
      jsonPointers:
        - /data
    - group: ""
      kind: PersistentVolumeClaim
      namespace: platform
      jsonPointers:
        - /status

