apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: automation
    app.kubernetes.io/name: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: automation
  source:
    repoURL: https://github.com/argoproj/argo-cd.git
    targetRevision: master
    path: manifests
    directory:
      include: "install.yaml"
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - Replace=true
  ignoreDifferences:
    # Ignore changes to secrets that Argo CD manages internally
    - group: ""
      kind: Secret
      name: argocd-secret
      jsonPointers:
        - /data
    - group: ""
      kind: Secret
      name: argocd-initial-admin-secret
      jsonPointers:
        - /data
    # Ignore configmaps that are updated by Argo CD
    - group: ""
      kind: ConfigMap
      jsonPointers:
        - /data
    # Ignore problematic annotations on CRDs that cause size limit issues
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration

