apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-parent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: platform
    app.kubernetes.io/name: platform-parent
spec:
  project: platform
  source:
    repoURL: ${GIT_REPO_URL}
    targetRevision: HEAD
    path: argocd/app-of-apps/apps/platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

